export type DocumentRecord = {
  id: string;
  title: string;
  category: string;
  status: string;
  format: string;
  duration: string;
  audience: string;
  brief: string;
  useWhen: string;
  url: string;
  sourceFiles: number;
};

export const documents: DocumentRecord[] = [
  {
    "id": "doc-91",
    "title": "AI Cost to Serve Framework",
    "category": "Foundation",
    "status": "Current",
    "format": "Document",
    "duration": "5–10 min brief",
    "audience": "Enterprise teams",
    "brief": "A decision framework for evaluating the real operating cost of AI, including infrastructure, tokens, enablement, oversight, and maintenance.",
    "useWhen": "Orienting leaders, defining value, establishing shared language, or setting policy.",
    "url": "https://docs.google.com/document/d/1mRYxeFGKesUsk8jU-YKSPcI-oe_O0yyS/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 1
  },
  {
    "id": "doc-88",
    "title": "Enterprise AI Customer Information Usage Policy Draft",
    "category": "Foundation",
    "status": "Current",
    "format": "Document",
    "duration": "5–10 min brief",
    "audience": "Enterprise teams",
    "brief": "A draft policy for using customer information in AI systems, focused on appropriate handling, boundaries, and enterprise responsibility.",
    "useWhen": "Orienting leaders, defining value, establishing shared language, or setting policy.",
    "url": "https://docs.google.com/document/d/1_68Krjefs4qdEtaahkGdGtPFHsdNWKfC/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 1
  },
  {
    "id": "doc-89",
    "title": "QUEST White Paper",
    "category": "Foundation",
    "status": "Current",
    "format": "Document",
    "duration": "5–10 min brief",
    "audience": "Leaders",
    "brief": "Explains QUEST, a five-question framework for locating enterprise AI value beyond the model itself.",
    "useWhen": "Orienting leaders, defining value, establishing shared language, or setting policy.",
    "url": "https://docs.google.com/document/d/1NOQHm-jPCwMFJup2uyVmKSJHS2bz_C-r/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 1
  },
  {
    "id": "doc-90",
    "title": "RampStack AI Vocabulary Glossary",
    "category": "Foundation",
    "status": "Current",
    "format": "Document",
    "duration": "5–10 min brief",
    "audience": "Enterprise teams",
    "brief": "A plain-language glossary that gives teams a shared vocabulary for models, agents, memory, retrieval, tools, risk, and governance.",
    "useWhen": "Orienting leaders, defining value, establishing shared language, or setting policy.",
    "url": "https://docs.google.com/document/d/1bIhrDmlXRBHAnVvkHt4sEp6wPT1oG3rt/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 1
  },
  {
    "id": "doc-86",
    "title": "RampStack Business Leaders AI Vocabulary",
    "category": "Foundation",
    "status": "Current",
    "format": "Document",
    "duration": "5–10 min brief",
    "audience": "Enterprise teams",
    "brief": "An executive-facing translation of AI concepts into business, operating, risk, and investment language.",
    "useWhen": "Orienting leaders, defining value, establishing shared language, or setting policy.",
    "url": "https://docs.google.com/document/d/1Yi4Ei6MIpv-PUjdiAV6IumRmRVeyJ0wo/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 1
  },
  {
    "id": "doc-117",
    "title": "RampStack System Map",
    "category": "Foundation",
    "status": "Current",
    "format": "Document",
    "duration": "5–10 min brief",
    "audience": "Enterprise teams",
    "brief": "The master orientation to the whole system. It connects the why, diagnosis, build, governance, leadership, and teaching layers into one enterprise lifecycle.",
    "useWhen": "Orienting leaders, defining value, establishing shared language, or setting policy.",
    "url": "https://docs.google.com/document/d/1oO8HTloY5-mtB_Dh-1ZfDqB-AHRYwkSi/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 1
  },
  {
    "id": "doc-92",
    "title": "RampStack V5 Internal Manual",
    "category": "Foundation",
    "status": "Current",
    "format": "Document",
    "duration": "5–10 min brief",
    "audience": "Enterprise teams",
    "brief": "The practitioner manual for Think, Build, Check: define the test, build the system, then verify it against the original intent.",
    "useWhen": "Orienting leaders, defining value, establishing shared language, or setting policy.",
    "url": "https://docs.google.com/document/d/1GEMvWdCZ9uEhdMJJjMPlJlUt97h0t-A9/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 1
  },
  {
    "id": "doc-85",
    "title": "Speaking the Language of the C",
    "category": "Foundation",
    "status": "Current",
    "format": "Document",
    "duration": "5–10 min brief",
    "audience": "Enterprise teams",
    "brief": "A foundation reference that helps teams frame enterprise AI in plain business language before choosing tools or projects.",
    "useWhen": "Orienting leaders, defining value, establishing shared language, or setting policy.",
    "url": "https://docs.google.com/document/d/1dR2yd4qSK6FuoanZvlUrATWQNcAQFLLf/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 2
  },
  {
    "id": "doc-83",
    "title": "Speaking the Language of the C-Suite - Editorial McKinsey Treatment",
    "category": "Foundation",
    "status": "Current",
    "format": "PDF",
    "duration": "5–10 min brief",
    "audience": "Leaders",
    "brief": "A foundation reference that helps teams frame enterprise AI in plain business language before choosing tools or projects.",
    "useWhen": "Orienting leaders, defining value, establishing shared language, or setting policy.",
    "url": "https://drive.google.com/file/d/1JAX28loGBnWxtHmuOnH6Rw4A7XDBVw9f/view?usp=drivesdk",
    "sourceFiles": 1
  },
  {
    "id": "doc-84",
    "title": "Speaking the Language of the C-Suite - McKinsey Treatment",
    "category": "Foundation",
    "status": "Current",
    "format": "PDF",
    "duration": "5–10 min brief",
    "audience": "Leaders",
    "brief": "A foundation reference that helps teams frame enterprise AI in plain business language before choosing tools or projects.",
    "useWhen": "Orienting leaders, defining value, establishing shared language, or setting policy.",
    "url": "https://drive.google.com/file/d/137Yu40z9HcvV7eOLlee7pyKCNn1KLCLe/view?usp=drivesdk",
    "sourceFiles": 4
  },
  {
    "id": "doc-93",
    "title": "The Burden Belongs To Us",
    "category": "Foundation",
    "status": "Current",
    "format": "Document",
    "duration": "5–10 min brief",
    "audience": "Enterprise teams",
    "brief": "A point of view on why AI teams must carry the burden of proving value rather than asking employees or business leaders to believe the promise.",
    "useWhen": "Orienting leaders, defining value, establishing shared language, or setting policy.",
    "url": "https://docs.google.com/document/d/1grrIFAeA6hiu-lcMiRJIjTlJ5-3-Bxgb/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 1
  },
  {
    "id": "doc-87",
    "title": "Updated Enterprise AI Playbook Recommendations",
    "category": "Foundation",
    "status": "Current",
    "format": "Document",
    "duration": "5–10 min brief",
    "audience": "Enterprise teams",
    "brief": "Recommendations for turning the framework into an enterprise playbook with clearer operating choices, governance, and adoption guidance.",
    "useWhen": "Orienting leaders, defining value, establishing shared language, or setting policy.",
    "url": "https://docs.google.com/document/d/1FvW8q0mLwopEU8Aqe4R7Gnjvc5THopL_/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 1
  },
  {
    "id": "doc-54",
    "title": "01 The Intelligence Layer Operational Diagnostic System",
    "category": "Intelligence Layer",
    "status": "Current",
    "format": "Document",
    "duration": "5–10 min brief",
    "audience": "AI enablement & process owners",
    "brief": "The operating model for diagnosing whether an organization has the context, source authority, permissions, and workflow legibility needed for AI.",
    "useWhen": "Diagnosing whether context, sources, permissions, and workflow signals are ready.",
    "url": "https://docs.google.com/document/d/1l5NgxA8BmIA1mnr_CjYeufZZ2IwIX8_D/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 1
  },
  {
    "id": "doc-55",
    "title": "02 The Work Beneath the Workflow Field Guide",
    "category": "Intelligence Layer",
    "status": "Current",
    "format": "Document",
    "duration": "5–10 min brief",
    "audience": "AI enablement & process owners",
    "brief": "A field guide for observing how work actually happens, including hidden judgment, handoffs, workarounds, and tacit knowledge.",
    "useWhen": "Diagnosing whether context, sources, permissions, and workflow signals are ready.",
    "url": "https://docs.google.com/document/d/1yyR_4RrexqwF74_8zOJ7C5zOy2tyRvBK/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 1
  },
  {
    "id": "doc-56",
    "title": "03 AI Readiness and Executive Reporting Framework",
    "category": "Intelligence Layer",
    "status": "Current",
    "format": "Document",
    "duration": "5–10 min brief",
    "audience": "Leaders",
    "brief": "Connects operational evidence to an executive-ready view of readiness, risk, opportunity, and recommended next moves.",
    "useWhen": "Diagnosing whether context, sources, permissions, and workflow signals are ready.",
    "url": "https://docs.google.com/document/d/1jWWhfFfuLovSwDgBA53MJx2jNsphN694/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 1
  },
  {
    "id": "doc-53",
    "title": "Enterprise AI Infrastructure Governance",
    "category": "Intelligence Layer",
    "status": "Current",
    "format": "Document",
    "duration": "5–10 min brief",
    "audience": "AI enablement & process owners",
    "brief": "Defines governance for the infrastructure around AI—not only models, but data, connectors, tools, permissions, memory, and runtime controls.",
    "useWhen": "Diagnosing whether context, sources, permissions, and workflow signals are ready.",
    "url": "https://docs.google.com/document/d/1b0J6_H6lqWVr7l62_QLekesd4Q3o5UxoZ52zPw2WQH4/edit?usp=drivesdk",
    "sourceFiles": 1
  },
  {
    "id": "doc-61",
    "title": "04 Intelligence Layer Engagement Playbook",
    "category": "Workflow Redesign",
    "status": "Current",
    "format": "Document",
    "duration": "5–10 min brief",
    "audience": "AI enablement & process owners",
    "brief": "A step-by-step engagement playbook for moving from executive intake through field observation, scoring, and executive reporting.",
    "useWhen": "Selecting work, observing reality, scoring readiness, or preparing an executive decision.",
    "url": "https://docs.google.com/document/d/1DNm88QLkUsOoxmfNWtUh-1gqhVJTm4qq/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 1
  },
  {
    "id": "doc-57",
    "title": "05 Executive Intake Questionnaire",
    "category": "Workflow Redesign",
    "status": "Current",
    "format": "Document",
    "duration": "Working tool",
    "audience": "Leaders",
    "brief": "A structured intake tool for aligning leaders on the business problem, scope, constraints, evidence, and decision required.",
    "useWhen": "Selecting work, observing reality, scoring readiness, or preparing an executive decision.",
    "url": "https://docs.google.com/document/d/11G0F6ipqMSV5Wl2Dmo_Qa6xcs5X-YSoC/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 1
  },
  {
    "id": "doc-59",
    "title": "06 Workflow Selection Worksheet",
    "category": "Workflow Redesign",
    "status": "Current",
    "format": "Document",
    "duration": "Working tool",
    "audience": "AI enablement & process owners",
    "brief": "A working tool for comparing candidate workflows and choosing where AI investigation or investment should begin.",
    "useWhen": "Selecting work, observing reality, scoring readiness, or preparing an executive decision.",
    "url": "https://docs.google.com/document/d/1585OsQ-7WHZxcVx3bPMRdWZsNVnIuqy8/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 1
  },
  {
    "id": "doc-58",
    "title": "07 Observation Protocol Field Notes Template",
    "category": "Workflow Redesign",
    "status": "Current",
    "format": "Document",
    "duration": "Working tool",
    "audience": "AI enablement & process owners",
    "brief": "A field-notes template for capturing real work, exceptions, systems, handoffs, and hidden judgment during observation.",
    "useWhen": "Selecting work, observing reality, scoring readiness, or preparing an executive decision.",
    "url": "https://docs.google.com/document/d/17MrlAOx5kKpZpmQ3fy40mGkEEbrHmliT/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 1
  },
  {
    "id": "doc-64",
    "title": "08 Hidden Work Interview Guide",
    "category": "Workflow Redesign",
    "status": "Current",
    "format": "Document",
    "duration": "5–10 min brief",
    "audience": "AI enablement & process owners",
    "brief": "Interview prompts for surfacing the invisible labor and local knowledge that formal process maps miss.",
    "useWhen": "Selecting work, observing reality, scoring readiness, or preparing an executive decision.",
    "url": "https://docs.google.com/document/d/1BhAvIQMqDZ2TRUz92OJutSSFVCW9D4at/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 1
  },
  {
    "id": "doc-60",
    "title": "09 System Reality Map Template",
    "category": "Workflow Redesign",
    "status": "Current",
    "format": "Document",
    "duration": "Working tool",
    "audience": "AI enablement & process owners",
    "brief": "A mapping tool for showing how work moves across people, systems, sources, approvals, and exceptions in practice.",
    "useWhen": "Selecting work, observing reality, scoring readiness, or preparing an executive decision.",
    "url": "https://docs.google.com/document/d/1LsjHVGMEtSzh35GETDG1Q3QfTqg3Bjoi/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 1
  },
  {
    "id": "doc-63",
    "title": "10 AI Readiness Scoring Rubric",
    "category": "Workflow Redesign",
    "status": "Current",
    "format": "Document",
    "duration": "Working tool",
    "audience": "Employees & facilitators",
    "brief": "A rubric for scoring whether a workflow has enough clarity, context, authority, and control to support responsible AI.",
    "useWhen": "Selecting work, observing reality, scoring readiness, or preparing an executive decision.",
    "url": "https://docs.google.com/document/d/1dO00TS35ueabUhXQt7UKNv9XnkvcjWZy/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 1
  },
  {
    "id": "doc-62",
    "title": "11 Executive Report Template",
    "category": "Workflow Redesign",
    "status": "Current",
    "format": "Document",
    "duration": "Working tool",
    "audience": "Leaders",
    "brief": "A reusable structure for translating diagnostic findings into a concise leadership decision document.",
    "useWhen": "Selecting work, observing reality, scoring readiness, or preparing an executive decision.",
    "url": "https://docs.google.com/document/d/1MGxxsod4pGJZjTCHNWkjAas2hBkYF8q3/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 1
  },
  {
    "id": "doc-13",
    "title": "architecture",
    "category": "Agent Build",
    "status": "Current",
    "format": "Working note",
    "duration": "5–10 min brief",
    "audience": "Builders & technical leads",
    "brief": "One part of a five-file technical audit, focused on architecture. It helps builders understand the current system before making changes.",
    "useWhen": "Scoping, specifying, building, or auditing an AI product or agent.",
    "url": "https://drive.google.com/file/d/1ou6J0parl53hAGRdZXR9MxS_FHFOUoV_/view?usp=drivesdk",
    "sourceFiles": 1
  },
  {
    "id": "doc-12",
    "title": "backend",
    "category": "Agent Build",
    "status": "Current",
    "format": "Working note",
    "duration": "5–10 min brief",
    "audience": "Builders & technical leads",
    "brief": "One part of a five-file technical audit, focused on backend. It helps builders understand the current system before making changes.",
    "useWhen": "Scoping, specifying, building, or auditing an AI product or agent.",
    "url": "https://drive.google.com/file/d/1f2EHR5I2PyBl6Bql_YnNZ0_83nfny2Q6/view?usp=drivesdk",
    "sourceFiles": 1
  },
  {
    "id": "doc-11",
    "title": "frontend",
    "category": "Agent Build",
    "status": "Current",
    "format": "Working note",
    "duration": "5–10 min brief",
    "audience": "Builders & technical leads",
    "brief": "One part of a five-file technical audit, focused on frontend. It helps builders understand the current system before making changes.",
    "useWhen": "Scoping, specifying, building, or auditing an AI product or agent.",
    "url": "https://drive.google.com/file/d/1rq1H_vdz1xrNM1tP9DGL5Ih2jNVT6XDF/view?usp=drivesdk",
    "sourceFiles": 1
  },
  {
    "id": "doc-16",
    "title": "RampStack Interview Agent PRD",
    "category": "Agent Build",
    "status": "Current",
    "format": "Document",
    "duration": "5–10 min brief",
    "audience": "Builders & technical leads",
    "brief": "Product requirements for a conversational agent that conducts a compressed Think/Build interview and produces a PRD plus a session record.",
    "useWhen": "Scoping, specifying, building, or auditing an AI product or agent.",
    "url": "https://docs.google.com/document/d/1McNxn8e6Md_7JRUjWVSdNnQT4-f4zUrv/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 1
  },
  {
    "id": "doc-18",
    "title": "RampStack Interview Question Guide",
    "category": "Agent Build",
    "status": "Current",
    "format": "Document",
    "duration": "5–10 min brief",
    "audience": "Leaders",
    "brief": "A practical reference focused on rampstack interview question guide, organized to help a reader understand the concept and decide when to use it.",
    "useWhen": "Scoping, specifying, building, or auditing an AI product or agent.",
    "url": "https://docs.google.com/document/d/1PcNQJigHMBWXPz_4dz9Ndbm3ThFDOmTE/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 1
  },
  {
    "id": "doc-15",
    "title": "RampStack V5 Build Type Profiles",
    "category": "Agent Build",
    "status": "Current",
    "format": "Document",
    "duration": "5–10 min brief",
    "audience": "Builders & technical leads",
    "brief": "Shows how Think, Build, Check changes across apps, autonomous agents, automations, skills, dashboards, and other build types.",
    "useWhen": "Scoping, specifying, building, or auditing an AI product or agent.",
    "url": "https://docs.google.com/document/d/1IuzBwh55_O08XqtCSPHooI6YbMqBW9ke/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 1
  },
  {
    "id": "doc-10",
    "title": "resolution",
    "category": "Agent Build",
    "status": "Current",
    "format": "Working note",
    "duration": "5–10 min brief",
    "audience": "Builders & technical leads",
    "brief": "One part of a five-file technical audit, focused on resolution. It helps builders understand the current system before making changes.",
    "useWhen": "Scoping, specifying, building, or auditing an AI product or agent.",
    "url": "https://drive.google.com/file/d/167ffjiczhi2KM9T-wnomkH-X7PcwCJRq/view?usp=drivesdk",
    "sourceFiles": 1
  },
  {
    "id": "doc-14",
    "title": "rsc-audit",
    "category": "Agent Build",
    "status": "Current",
    "format": "Working note",
    "duration": "5–10 min brief",
    "audience": "Builders & technical leads",
    "brief": "A practical reference focused on rsc-audit, organized to help a reader understand the concept and decide when to use it.",
    "useWhen": "Scoping, specifying, building, or auditing an AI product or agent.",
    "url": "https://drive.google.com/file/d/1cPtEQGH_54DIwwuUHG6_4n04NPN7VYtb/view?usp=drivesdk",
    "sourceFiles": 1
  },
  {
    "id": "doc-9",
    "title": "scalability",
    "category": "Agent Build",
    "status": "Current",
    "format": "Working note",
    "duration": "5–10 min brief",
    "audience": "Builders & technical leads",
    "brief": "One part of a five-file technical audit, focused on scalability. It helps builders understand the current system before making changes.",
    "useWhen": "Scoping, specifying, building, or auditing an AI product or agent.",
    "url": "https://drive.google.com/file/d/1VJYV4cXP5AxsjxT663CoumANjKgJvaR4/view?usp=drivesdk",
    "sourceFiles": 1
  },
  {
    "id": "doc-17",
    "title": "The agent has two personalities inside one system",
    "category": "Agent Build",
    "status": "Current",
    "format": "Document",
    "duration": "5–10 min brief",
    "audience": "Builders & technical leads",
    "brief": "Explores how one agent can separate conversational guidance from structured system behavior without losing control or traceability.",
    "useWhen": "Scoping, specifying, building, or auditing an AI product or agent.",
    "url": "https://docs.google.com/document/d/11tPTnheRhlZwxVpdmgMVkKrDHwrmdSdB/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 1
  },
  {
    "id": "doc-24",
    "title": "Agent Orchestration Patterns",
    "category": "Agent Orchestration",
    "status": "Current",
    "format": "Working note",
    "duration": "5–10 min brief",
    "audience": "Builders & technical leads",
    "brief": "A practical orchestration chapter focused on agent orchestration patterns, translating shipped-system lessons into safer agent design and operations.",
    "useWhen": "Designing run loops, tools, approvals, observability, evaluation, and multi-agent boundaries.",
    "url": "https://drive.google.com/file/d/1uJ_q2lUkAALLPeUxhU8n6kQwQQLfvsVz/view?usp=drivesdk",
    "sourceFiles": 1
  },
  {
    "id": "doc-20",
    "title": "Agent Orchestration Series Index",
    "category": "Agent Orchestration",
    "status": "Current",
    "format": "Working note",
    "duration": "5–10 min brief",
    "audience": "Builders & technical leads",
    "brief": "The reading map for the orchestration series, grounded in external guidance and lessons from shipped agent systems.",
    "useWhen": "Designing run loops, tools, approvals, observability, evaluation, and multi-agent boundaries.",
    "url": "https://drive.google.com/file/d/13IqT-EdP-C78zJOErShTGclIKeyUxheI/view?usp=drivesdk",
    "sourceFiles": 1
  },
  {
    "id": "doc-21",
    "title": "Agent Project Playbook",
    "category": "Agent Orchestration",
    "status": "Current",
    "format": "Working note",
    "duration": "5–10 min brief",
    "audience": "Builders & technical leads",
    "brief": "A practical project sequence: decide whether an agent is needed, define value, set authority, map sources, design tools, choose orchestration, and audit.",
    "useWhen": "Designing run loops, tools, approvals, observability, evaluation, and multi-agent boundaries.",
    "url": "https://drive.google.com/file/d/1bL4mJZqP8d4gt20UvV1k91VSTGhTYWpr/view?usp=drivesdk",
    "sourceFiles": 1
  },
  {
    "id": "doc-26",
    "title": "Blind Spots Checklist",
    "category": "Agent Orchestration",
    "status": "Current",
    "format": "Working note",
    "duration": "5–10 min brief",
    "audience": "Builders & technical leads",
    "brief": "A practical orchestration chapter focused on blind spots checklist, translating shipped-system lessons into safer agent design and operations.",
    "useWhen": "Designing run loops, tools, approvals, observability, evaluation, and multi-agent boundaries.",
    "url": "https://drive.google.com/file/d/1O_lZjzciFlHaC1GVFGny1XdVQuEReb1t/view?usp=drivesdk",
    "sourceFiles": 1
  },
  {
    "id": "doc-23",
    "title": "Evals, Beta, And Final Audit",
    "category": "Agent Orchestration",
    "status": "Current",
    "format": "Working note",
    "duration": "5–10 min brief",
    "audience": "Builders & technical leads",
    "brief": "A practical orchestration chapter focused on evals, beta, and final audit, translating shipped-system lessons into safer agent design and operations.",
    "useWhen": "Designing run loops, tools, approvals, observability, evaluation, and multi-agent boundaries.",
    "url": "https://drive.google.com/file/d/1b7RIq_aw58ekFvgWnFWerHus9yF8lUIB/view?usp=drivesdk",
    "sourceFiles": 1
  },
  {
    "id": "doc-27",
    "title": "Memory, Context, And Source Of Truth",
    "category": "Agent Orchestration",
    "status": "Current",
    "format": "Working note",
    "duration": "5–10 min brief",
    "audience": "Builders & technical leads",
    "brief": "A practical orchestration chapter focused on memory, context, and source of truth, translating shipped-system lessons into safer agent design and operations.",
    "useWhen": "Designing run loops, tools, approvals, observability, evaluation, and multi-agent boundaries.",
    "url": "https://drive.google.com/file/d/1X6dsOaq5pNo_jOggyKq884Lsp8UYTrUb/view?usp=drivesdk",
    "sourceFiles": 1
  },
  {
    "id": "doc-22",
    "title": "Mission Control, Logs, And Operator View",
    "category": "Agent Orchestration",
    "status": "Current",
    "format": "Working note",
    "duration": "5–10 min brief",
    "audience": "Builders & technical leads",
    "brief": "A practical orchestration chapter focused on mission control, logs, and operator view, translating shipped-system lessons into safer agent design and operations.",
    "useWhen": "Designing run loops, tools, approvals, observability, evaluation, and multi-agent boundaries.",
    "url": "https://drive.google.com/file/d/1qJyb2HuhAyVZcY4bjI16X4XgzdL9R_kQ/view?usp=drivesdk",
    "sourceFiles": 1
  },
  {
    "id": "doc-30",
    "title": "Multi-Agent Design Without Chaos",
    "category": "Agent Orchestration",
    "status": "Current",
    "format": "Working note",
    "duration": "5–10 min brief",
    "audience": "Builders & technical leads",
    "brief": "A practical orchestration chapter focused on multi-agent design without chaos, translating shipped-system lessons into safer agent design and operations.",
    "useWhen": "Designing run loops, tools, approvals, observability, evaluation, and multi-agent boundaries.",
    "url": "https://drive.google.com/file/d/1qxg9jYLlToBA7KHwg6vuuiI0Zgsz3o4O/view?usp=drivesdk",
    "sourceFiles": 1
  },
  {
    "id": "doc-25",
    "title": "RampStack Agent Interview Guidance",
    "category": "Agent Orchestration",
    "status": "Current",
    "format": "Working note",
    "duration": "5–10 min brief",
    "audience": "Builders & technical leads",
    "brief": "A practical orchestration chapter focused on rampstack agent interview guidance, translating shipped-system lessons into safer agent design and operations.",
    "useWhen": "Designing run loops, tools, approvals, observability, evaluation, and multi-agent boundaries.",
    "url": "https://drive.google.com/file/d/1-2RjIC69gEFvaWZVhRVGu1XXaqfGsqqG/view?usp=drivesdk",
    "sourceFiles": 1
  },
  {
    "id": "doc-29",
    "title": "Start With The System, Not The Model",
    "category": "Agent Orchestration",
    "status": "Current",
    "format": "Working note",
    "duration": "5–10 min brief",
    "audience": "Builders & technical leads",
    "brief": "A practical orchestration chapter focused on start with the system, not the model, translating shipped-system lessons into safer agent design and operations.",
    "useWhen": "Designing run loops, tools, approvals, observability, evaluation, and multi-agent boundaries.",
    "url": "https://drive.google.com/file/d/1PxkNxuFJQeI1Z3geKN9MBLBHIqbfxrfN/view?usp=drivesdk",
    "sourceFiles": 1
  },
  {
    "id": "doc-28",
    "title": "Tools, Actions, And Guardrails",
    "category": "Agent Orchestration",
    "status": "Current",
    "format": "Working note",
    "duration": "5–10 min brief",
    "audience": "Builders & technical leads",
    "brief": "A practical orchestration chapter focused on tools, actions, and guardrails, translating shipped-system lessons into safer agent design and operations.",
    "useWhen": "Designing run loops, tools, approvals, observability, evaluation, and multi-agent boundaries.",
    "url": "https://drive.google.com/file/d/1QfIiYcKSsaq5gE9QPMkQ6jzGOYfIsoP6/view?usp=drivesdk",
    "sourceFiles": 1
  },
  {
    "id": "doc-19",
    "title": "Why Agent Orchestration Matters",
    "category": "Agent Orchestration",
    "status": "Current",
    "format": "Working note",
    "duration": "5–10 min brief",
    "audience": "Builders & technical leads",
    "brief": "Introduces orchestration as the discipline of making delegated work observable, bounded, reviewable, and trustworthy.",
    "useWhen": "Designing run loops, tools, approvals, observability, evaluation, and multi-agent boundaries.",
    "url": "https://drive.google.com/file/d/1fc8rH_kCrA1EJMBH3N5iJCfw_wDK1iEl/view?usp=drivesdk",
    "sourceFiles": 1
  },
  {
    "id": "doc-47",
    "title": "Chapter 1 - AI Agents Have a Memory Problem",
    "category": "Memory Architecture",
    "status": "Current",
    "format": "Document",
    "duration": "Reference",
    "audience": "Builders & technical leads",
    "brief": "Frames the central memory question—what an agent should remember—and separates it from model and framework selection.",
    "useWhen": "Designing what an agent remembers, how it retrieves evidence, and what it must not store.",
    "url": "https://docs.google.com/document/d/17G5bUf8c21YaPlOThxvPdj77diHuXVMV/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 1
  },
  {
    "id": "doc-38",
    "title": "Chapter 10 - Right-Sizing Your Memory Architecture",
    "category": "Memory Architecture",
    "status": "Current",
    "format": "Document",
    "duration": "Reference",
    "audience": "Builders & technical leads",
    "brief": "A guide to making complexity earn its place by matching memory and retrieval architecture to the real work.",
    "useWhen": "Designing what an agent remembers, how it retrieves evidence, and what it must not store.",
    "url": "https://docs.google.com/document/d/14pp6FOgAUZuurvKkCYOlUhBHM8mTOoZ1/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 1
  },
  {
    "id": "doc-46",
    "title": "Chapter 2 - Memory and Retrieval",
    "category": "Memory Architecture",
    "status": "Current",
    "format": "Document",
    "duration": "Reference",
    "audience": "Builders & technical leads",
    "brief": "Part of the AI memory series. Explains memory and retrieval and turns the concept into practical architecture decisions.",
    "useWhen": "Designing what an agent remembers, how it retrieves evidence, and what it must not store.",
    "url": "https://docs.google.com/document/d/1_B46Avvko2YBHjtZyRB_yx41QC9Bdydm/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 1
  },
  {
    "id": "doc-45",
    "title": "Chapter 3 - Memory Is More Than Documents",
    "category": "Memory Architecture",
    "status": "Current",
    "format": "Document",
    "duration": "Reference",
    "audience": "Builders & technical leads",
    "brief": "Part of the AI memory series. Explains memory is more than documents and turns the concept into practical architecture decisions.",
    "useWhen": "Designing what an agent remembers, how it retrieves evidence, and what it must not store.",
    "url": "https://docs.google.com/document/d/1DjjjUroOL9S9Yt1ZglqEMrpOE5rJNvvO/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 1
  },
  {
    "id": "doc-44",
    "title": "Chapter 4 - Finding the Right Needle",
    "category": "Memory Architecture",
    "status": "Current",
    "format": "Document",
    "duration": "Reference",
    "audience": "Builders & technical leads",
    "brief": "Part of the AI memory series. Explains finding the right needle and turns the concept into practical architecture decisions.",
    "useWhen": "Designing what an agent remembers, how it retrieves evidence, and what it must not store.",
    "url": "https://docs.google.com/document/d/1b1baIkMCXDhIYI1KRw81qtRjfum_C4h4/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 1
  },
  {
    "id": "doc-43",
    "title": "Chapter 5 - The Building Blocks of Memory",
    "category": "Memory Architecture",
    "status": "Current",
    "format": "Document",
    "duration": "Reference",
    "audience": "Builders & technical leads",
    "brief": "Part of the AI memory series. Explains the building blocks of memory and turns the concept into practical architecture decisions.",
    "useWhen": "Designing what an agent remembers, how it retrieves evidence, and what it must not store.",
    "url": "https://docs.google.com/document/d/1_-dMZlIVrJTadn05Rr7S5tEpD8Id2pa_/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 1
  },
  {
    "id": "doc-42",
    "title": "Chapter 6 - The Building Blocks of Retrieval",
    "category": "Memory Architecture",
    "status": "Current",
    "format": "Document",
    "duration": "Reference",
    "audience": "Builders & technical leads",
    "brief": "Part of the AI memory series. Explains the building blocks of retrieval and turns the concept into practical architecture decisions.",
    "useWhen": "Designing what an agent remembers, how it retrieves evidence, and what it must not store.",
    "url": "https://docs.google.com/document/d/17knYMFGE_mTY0rPxBF5kvpH-xJRpS5rd/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 1
  },
  {
    "id": "doc-41",
    "title": "Chapter 7 - The Five Questions That Shape Your Memory Strategy",
    "category": "Memory Architecture",
    "status": "Current",
    "format": "Document",
    "duration": "Reference",
    "audience": "Leaders",
    "brief": "Five questions that narrow what memory an agent actually needs before a team chooses storage technology.",
    "useWhen": "Designing what an agent remembers, how it retrieves evidence, and what it must not store.",
    "url": "https://docs.google.com/document/d/19pm2ibrGhDtddySktlERHyjg2Gvt_vfG/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 1
  },
  {
    "id": "doc-40",
    "title": "Chapter 8 - The Five Questions That Shape Your Retrieval Strategy",
    "category": "Memory Architecture",
    "status": "Current",
    "format": "Document",
    "duration": "Reference",
    "audience": "Leaders",
    "brief": "Five questions for deciding how an agent should find current, authoritative, permission-appropriate evidence.",
    "useWhen": "Designing what an agent remembers, how it retrieves evidence, and what it must not store.",
    "url": "https://docs.google.com/document/d/1snMTmJrToCBK-6xcGq3jNg3axthOFYk2/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 1
  },
  {
    "id": "doc-39",
    "title": "Chapter 9 - Putting the Framework to Work",
    "category": "Memory Architecture",
    "status": "Current",
    "format": "Document",
    "duration": "Reference",
    "audience": "Builders & technical leads",
    "brief": "Part of the AI memory series. Explains putting the framework to work and turns the concept into practical architecture decisions.",
    "useWhen": "Designing what an agent remembers, how it retrieves evidence, and what it must not store.",
    "url": "https://docs.google.com/document/d/16VC0vA21qaE5-dctuUk9904z5khC1kf1/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 1
  },
  {
    "id": "doc-108",
    "title": "Do Not Store Guidance",
    "category": "Memory Architecture",
    "status": "Current",
    "format": "Working note",
    "duration": "Reference",
    "audience": "Builders & technical leads",
    "brief": "A memory and retrieval reference focused on do not store guidance, intended to keep agent architecture proportional, permission-aware, and maintainable.",
    "useWhen": "Designing what an agent remembers, how it retrieves evidence, and what it must not store.",
    "url": "https://drive.google.com/file/d/1SRyasOxYZXSswdNUWwcfDipuRnxxvOwH/view?usp=drivesdk",
    "sourceFiles": 1
  },
  {
    "id": "doc-110",
    "title": "Final Audit Evidence Requirements",
    "category": "Memory Architecture",
    "status": "Current",
    "format": "Working note",
    "duration": "Reference",
    "audience": "Builders & technical leads",
    "brief": "A memory and retrieval reference focused on final audit evidence requirements, intended to keep agent architecture proportional, permission-aware, and maintainable.",
    "useWhen": "Designing what an agent remembers, how it retrieves evidence, and what it must not store.",
    "url": "https://drive.google.com/file/d/10DK0CWSD9c0bPSw8kFDqxnSAvM6QkJ1P/view?usp=drivesdk",
    "sourceFiles": 1
  },
  {
    "id": "doc-111",
    "title": "Memory Build Readiness Index",
    "category": "Memory Architecture",
    "status": "Current",
    "format": "Working note",
    "duration": "Reference",
    "audience": "Employees & facilitators",
    "brief": "A memory and retrieval reference focused on memory build readiness index, intended to keep agent architecture proportional, permission-aware, and maintainable.",
    "useWhen": "Designing what an agent remembers, how it retrieves evidence, and what it must not store.",
    "url": "https://drive.google.com/file/d/1Ckko7vpxvUtv2U2oOUnvQGum9tXFrqMP/view?usp=drivesdk",
    "sourceFiles": 1
  },
  {
    "id": "doc-112",
    "title": "Memory Inventory Template",
    "category": "Memory Architecture",
    "status": "Current",
    "format": "Working note",
    "duration": "Working tool",
    "audience": "Builders & technical leads",
    "brief": "A working tool for memory inventory template. Use it to capture evidence consistently and produce a decision-ready output.",
    "useWhen": "Designing what an agent remembers, how it retrieves evidence, and what it must not store.",
    "url": "https://drive.google.com/file/d/1Y0bDcuAR-5Aoy8ZLCkfZSYBCw7RWTT4g/view?usp=drivesdk",
    "sourceFiles": 1
  },
  {
    "id": "doc-107",
    "title": "Permission Model Placeholder",
    "category": "Memory Architecture",
    "status": "Current",
    "format": "Working note",
    "duration": "Reference",
    "audience": "Builders & technical leads",
    "brief": "A memory and retrieval reference focused on permission model placeholder, intended to keep agent architecture proportional, permission-aware, and maintainable.",
    "useWhen": "Designing what an agent remembers, how it retrieves evidence, and what it must not store.",
    "url": "https://drive.google.com/file/d/1VHEiDdydCzcsEwZoSk2byCbYB6zg7ow5/view?usp=drivesdk",
    "sourceFiles": 1
  },
  {
    "id": "doc-109",
    "title": "RampStack Build Profile Memory Mapping",
    "category": "Memory Architecture",
    "status": "Current",
    "format": "Working note",
    "duration": "Reference",
    "audience": "Builders & technical leads",
    "brief": "A memory and retrieval reference focused on rampstack build profile memory mapping, intended to keep agent architecture proportional, permission-aware, and maintainable.",
    "useWhen": "Designing what an agent remembers, how it retrieves evidence, and what it must not store.",
    "url": "https://drive.google.com/file/d/1SFs0viph_xHJjdv_Q3pfzXyCXFGddFgE/view?usp=drivesdk",
    "sourceFiles": 1
  },
  {
    "id": "doc-106",
    "title": "Retrieval Decision Matrix",
    "category": "Memory Architecture",
    "status": "Current",
    "format": "Working note",
    "duration": "Reference",
    "audience": "Builders & technical leads",
    "brief": "A memory and retrieval reference focused on retrieval decision matrix, intended to keep agent architecture proportional, permission-aware, and maintainable.",
    "useWhen": "Designing what an agent remembers, how it retrieves evidence, and what it must not store.",
    "url": "https://drive.google.com/file/d/11CvI9CuLuNvENaxSyur9z1kathkY3O2V/view?usp=drivesdk",
    "sourceFiles": 1
  },
  {
    "id": "doc-37",
    "title": "Where AI Memory Goes Next",
    "category": "Memory Architecture",
    "status": "Current",
    "format": "Document",
    "duration": "Reference",
    "audience": "Builders & technical leads",
    "brief": "A forward-looking view of how agent memory, retrieval, source authority, and enterprise systems may evolve.",
    "useWhen": "Designing what an agent remembers, how it retrieves evidence, and what it must not store.",
    "url": "https://docs.google.com/document/d/17Pp7LM0cHG16X9VyBeeRV0KO6_-RO1pl/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 1
  },
  {
    "id": "doc-52",
    "title": "AI Enablement Presentation",
    "category": "AI Academy",
    "status": "Current",
    "format": "Deck",
    "duration": "5–10 min brief",
    "audience": "Employees & facilitators",
    "brief": "A practical reference focused on ai enablement presentation, organized to help a reader understand the concept and decide when to use it.",
    "useWhen": "Choosing or delivering a learning experience for employees, managers, builders, or leaders.",
    "url": "https://docs.google.com/presentation/d/1i_mG10MZ_uenMDR_b_J5H45v5X3cZZZo/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 1
  },
  {
    "id": "doc-33",
    "title": "AI Readiness One Day Workshop",
    "category": "AI Academy",
    "status": "Current",
    "format": "Document",
    "duration": "1-day program",
    "audience": "Employees & facilitators",
    "brief": "A beginner-friendly day that builds the floor: what AI is, where it is safe, how to prompt, and which tasks are suitable starting points.",
    "useWhen": "Choosing or delivering a learning experience for employees, managers, builders, or leaders.",
    "url": "https://docs.google.com/document/d/1MYmIMIqzA3MCBp1RkR29EIXN9Ebxknvf/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 2
  },
  {
    "id": "doc-36",
    "title": "AI Workshop TwoDay",
    "category": "AI Academy",
    "status": "Current",
    "format": "Document",
    "duration": "2-day program",
    "audience": "Employees & facilitators",
    "brief": "A two-day employee experience that moves from first contact to a Golden Stake project reviewed by Legal, IT, and AI Enablement.",
    "useWhen": "Choosing or delivering a learning experience for employees, managers, builders, or leaders.",
    "url": "https://docs.google.com/document/d/143-AwGXgNsSuCMJLZ8cByMf4HAn2snw5/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 2
  },
  {
    "id": "doc-101",
    "title": "ai-academy-landing-directions",
    "category": "AI Academy",
    "status": "Current",
    "format": "Interactive",
    "duration": "5–10 min brief",
    "audience": "Employees & facilitators",
    "brief": "A practical reference focused on ai-academy-landing-directions, organized to help a reader understand the concept and decide when to use it.",
    "useWhen": "Choosing or delivering a learning experience for employees, managers, builders, or leaders.",
    "url": "https://drive.google.com/file/d/1ZQeux-2Qn457g_BN9CXnhG0N04H2TWJI/view?usp=drivesdk",
    "sourceFiles": 1
  },
  {
    "id": "doc-102",
    "title": "Alignment Function Lecture",
    "category": "AI Academy",
    "status": "Current",
    "format": "Deck",
    "duration": "5–10 min brief",
    "audience": "Employees & facilitators",
    "brief": "A practical reference focused on alignment function lecture, organized to help a reader understand the concept and decide when to use it.",
    "useWhen": "Choosing or delivering a learning experience for employees, managers, builders, or leaders.",
    "url": "https://docs.google.com/presentation/d/16xUaEvjMut9KKKO7We5PEfOK46Vqj9ku/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 1
  },
  {
    "id": "doc-95",
    "title": "Building Autonomous Agents Employee Spotlight",
    "category": "AI Academy",
    "status": "Current",
    "format": "Document",
    "duration": "5–10 min brief",
    "audience": "Employees & facilitators",
    "brief": "An employee-focused course on how autonomous agents work, where they fit, and how to build them responsibly.",
    "useWhen": "Choosing or delivering a learning experience for employees, managers, builders, or leaders.",
    "url": "https://docs.google.com/document/d/1L7XB03TPr7IJV-UZCqf7sjj1miMwEhJPIk8R4IrH3xQ/edit?usp=drivesdk",
    "sourceFiles": 1
  },
  {
    "id": "doc-31",
    "title": "Building Deploying Your First Agent",
    "category": "AI Academy",
    "status": "Current",
    "format": "Document",
    "duration": "1-day program",
    "audience": "Employees & facilitators",
    "brief": "A standalone full-day build session that tests whether an agent is warranted and produces a bounded sandbox deployment.",
    "useWhen": "Choosing or delivering a learning experience for employees, managers, builders, or leaders.",
    "url": "https://docs.google.com/document/d/1s6hd1hQgRR6ySr3e-f2Q7jS84bduQ9Hw/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 1
  },
  {
    "id": "doc-116",
    "title": "design-system",
    "category": "AI Academy",
    "status": "Current",
    "format": "Working note",
    "duration": "5–10 min brief",
    "audience": "Employees & facilitators",
    "brief": "A practical reference focused on design-system, organized to help a reader understand the concept and decide when to use it.",
    "useWhen": "Choosing or delivering a learning experience for employees, managers, builders, or leaders.",
    "url": "https://drive.google.com/file/d/1-CfWLTaK6FPuvQI57UBXOyWbf0PMbttP/view?usp=drivesdk",
    "sourceFiles": 1
  },
  {
    "id": "doc-98",
    "title": "Does the Math Work Field Guide",
    "category": "AI Academy",
    "status": "Current",
    "format": "Document",
    "duration": "5–10 min brief",
    "audience": "Employees & facilitators",
    "brief": "A facilitator-ready field guide for does the math work, with questions and exercises that turn the concept into action.",
    "useWhen": "Choosing or delivering a learning experience for employees, managers, builders, or leaders.",
    "url": "https://docs.google.com/document/d/12kmqG9tCk-ePuggLD5ySaYjzLbhr-iWJ/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 2
  },
  {
    "id": "doc-94",
    "title": "Executive Training Syllabus V2",
    "category": "AI Academy",
    "status": "Current",
    "format": "Document",
    "duration": "5–10 min brief",
    "audience": "Leaders",
    "brief": "An enterprise operations syllabus covering secure workspaces, model and budget choices, reusable skills, automation, and interactive dashboards.",
    "useWhen": "Choosing or delivering a learning experience for employees, managers, builders, or leaders.",
    "url": "https://docs.google.com/document/d/14PZegeApNxVh5pV6tVJ6J8ioJrfRYZ2ULjoPRN-4eM4/edit?usp=drivesdk",
    "sourceFiles": 1
  },
  {
    "id": "doc-97",
    "title": "Good Data In Field Guide",
    "category": "AI Academy",
    "status": "Current",
    "format": "Document",
    "duration": "5–10 min brief",
    "audience": "Employees & facilitators",
    "brief": "A facilitator-ready field guide for good data in, with questions and exercises that turn the concept into action.",
    "useWhen": "Choosing or delivering a learning experience for employees, managers, builders, or leaders.",
    "url": "https://docs.google.com/document/d/1fMfM-0KdWAmVRbEPsejiCYZLfz23LHJe/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 2
  },
  {
    "id": "doc-34",
    "title": "IGNITE Workshop OneDay",
    "category": "AI Academy",
    "status": "Current",
    "format": "Document",
    "duration": "1-day program",
    "audience": "Employees & facilitators",
    "brief": "A one-day build intensive that turns employee expertise into a working AI solution, then documents and stress-tests it.",
    "useWhen": "Choosing or delivering a learning experience for employees, managers, builders, or leaders.",
    "url": "https://docs.google.com/document/d/1plyYmbN4p1qQBTSMZbubgfaqimCQslFd/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 2
  },
  {
    "id": "doc-32",
    "title": "Manager AI Orientation",
    "category": "AI Academy",
    "status": "Current",
    "format": "Document",
    "duration": "90 min session",
    "audience": "Managers",
    "brief": "A 90-minute manager session on what good AI adoption looks like, where human judgment stays essential, and how to answer safe-use questions.",
    "useWhen": "Choosing or delivering a learning experience for employees, managers, builders, or leaders.",
    "url": "https://docs.google.com/document/d/1nMUpjw1X0gyRXAH7RRnKSY0oNBzKB4fy/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 2
  },
  {
    "id": "doc-2",
    "title": "Miller AI Academy - Options.dc",
    "category": "AI Academy",
    "status": "Current",
    "format": "Interactive",
    "duration": "5–10 min brief",
    "audience": "Employees & facilitators",
    "brief": "Design and content alternatives used to shape the Miller AI Academy experience.",
    "useWhen": "Choosing or delivering a learning experience for employees, managers, builders, or leaders.",
    "url": "https://drive.google.com/file/d/1_GkRYhj6Dcxtvt29pSxelRopTCxFSw7f/view?usp=drivesdk",
    "sourceFiles": 1
  },
  {
    "id": "doc-1",
    "title": "Miller AI Academy.dc",
    "category": "AI Academy",
    "status": "Current",
    "format": "Interactive",
    "duration": "5–10 min brief",
    "audience": "Employees & facilitators",
    "brief": "The integrated Academy experience that organizes employee, manager, builder, and leadership learning into clear paths and outcomes.",
    "useWhen": "Choosing or delivering a learning experience for employees, managers, builders, or leaders.",
    "url": "https://drive.google.com/file/d/1ujr_0Qwxjtc_Q2-0i7HtSiuND993Z8LX/view?usp=drivesdk",
    "sourceFiles": 1
  },
  {
    "id": "doc-96",
    "title": "QUEST Field Guide",
    "category": "AI Academy",
    "status": "Current",
    "format": "Document",
    "duration": "5–10 min brief",
    "audience": "Leaders",
    "brief": "A facilitator-ready field guide for quest, with questions and exercises that turn the concept into action.",
    "useWhen": "Choosing or delivering a learning experience for employees, managers, builders, or leaders.",
    "url": "https://docs.google.com/document/d/1WHy1Kv4-ui8TFccaOXTtrXAcTXc4lkik/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 2
  },
  {
    "id": "doc-100",
    "title": "The Alignment Function",
    "category": "AI Academy",
    "status": "Current",
    "format": "Deck",
    "duration": "5–10 min brief",
    "audience": "Employees & facilitators",
    "brief": "A practical reference focused on the alignment function, organized to help a reader understand the concept and decide when to use it.",
    "useWhen": "Choosing or delivering a learning experience for employees, managers, builders, or leaders.",
    "url": "https://docs.google.com/presentation/d/1W849hMj9iRoKfqDl24iiTiWEd7KzAz8V/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 1
  },
  {
    "id": "doc-99",
    "title": "The Golden Stake Field Guide",
    "category": "AI Academy",
    "status": "Current",
    "format": "Document",
    "duration": "5–10 min brief",
    "audience": "Leaders",
    "brief": "A facilitator-ready field guide for the golden stake, with questions and exercises that turn the concept into action.",
    "useWhen": "Choosing or delivering a learning experience for employees, managers, builders, or leaders.",
    "url": "https://docs.google.com/document/d/1mJ1FslEBPswSO87jz0C5t54mpuDzk1hX/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 2
  },
  {
    "id": "doc-35",
    "title": "Work Redesign Toolkit Intensive",
    "category": "AI Academy",
    "status": "Current",
    "format": "Document",
    "duration": "2-day program",
    "audience": "Employees & facilitators",
    "brief": "A two-day practitioner intensive for uncovering hidden work and deciding what to automate, support, or protect.",
    "useWhen": "Choosing or delivering a learning experience for employees, managers, builders, or leaders.",
    "url": "https://docs.google.com/document/d/1oMhGHRr405vvvBD-gZ7kI0Y-EKObrSff/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 2
  },
  {
    "id": "doc-8",
    "title": "Heroes and Duct Tape Keynote Outline",
    "category": "Leadership",
    "status": "Current",
    "format": "Document",
    "duration": "45 min talk",
    "audience": "Leaders",
    "brief": "A leadership keynote on seeing the real work—heroics, exceptions, and invisible labor—before automating it.",
    "useWhen": "Preparing leaders to fund, govern, protect, and communicate AI-enabled change.",
    "url": "https://docs.google.com/document/d/1b6Wp4aTz0RlK9UPkTvdtncsQLGTflkJi/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 2
  },
  {
    "id": "doc-5",
    "title": "Home Ground Keynote Outline",
    "category": "Leadership",
    "status": "Current",
    "format": "Document",
    "duration": "45 min talk",
    "audience": "Leaders",
    "brief": "A leadership keynote about earning authority by speaking the business’s language and protecting the craft that makes the operation work.",
    "useWhen": "Preparing leaders to fund, govern, protect, and communicate AI-enabled change.",
    "url": "https://docs.google.com/document/d/1EYDqsVWVWAIlIGCdvV3M4spmVMa2s4Vb/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 2
  },
  {
    "id": "doc-3",
    "title": "James Manning Leadership OnePager",
    "category": "Leadership",
    "status": "Current",
    "format": "Document",
    "duration": "5–10 min brief",
    "audience": "Leaders",
    "brief": "A concise overview of the leadership platform, signature talks, operating themes, and intended executive outcomes.",
    "useWhen": "Preparing leaders to fund, govern, protect, and communicate AI-enabled change.",
    "url": "https://docs.google.com/document/d/1fnzJrhMzqfNDieOHKMN3L20s3FloWjoa/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 2
  },
  {
    "id": "doc-4",
    "title": "QUEST Keynote Manuscript Draft",
    "category": "Leadership",
    "status": "Current",
    "format": "Document",
    "duration": "45 min talk",
    "audience": "Leaders",
    "brief": "A leadership talk that translates quest into an enterprise decision and operating outcome.",
    "useWhen": "Preparing leaders to fund, govern, protect, and communicate AI-enabled change.",
    "url": "https://docs.google.com/document/d/1p64KztNRCzxYs6-JTmoXr2qJ8fbW53-E/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 2
  },
  {
    "id": "doc-6",
    "title": "QUEST Keynote Outline",
    "category": "Leadership",
    "status": "Current",
    "format": "Document",
    "duration": "45 min talk",
    "audience": "Leaders",
    "brief": "A leadership keynote using five questions to locate enterprise AI value beyond the model.",
    "useWhen": "Preparing leaders to fund, govern, protect, and communicate AI-enabled change.",
    "url": "https://docs.google.com/document/d/1CnaHcp__fv6X7Qb_7Z8IkRJ1d-YhiKzQ/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 2
  },
  {
    "id": "doc-7",
    "title": "The Golden Stake Keynote Outline",
    "category": "Leadership",
    "status": "Current",
    "format": "Document",
    "duration": "45 min talk",
    "audience": "Leaders",
    "brief": "A leadership keynote and legitimacy test: establish a baseline, define the claim, set the boundary, and decide what would make the effort not worth continuing.",
    "useWhen": "Preparing leaders to fund, govern, protect, and communicate AI-enabled change.",
    "url": "https://docs.google.com/document/d/1fGoib3CJLWc9l72RONxAxOXy4_PXZRDZ/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 2
  },
  {
    "id": "doc-74",
    "title": "Agentic Workbenches Enterprise Codex White Paper",
    "category": "Research & Signals",
    "status": "Reference",
    "format": "Document",
    "duration": "Reference",
    "audience": "Strategy & research teams",
    "brief": "A research or strategy reference on agentic workbenches enterprise codex, used to ground decisions in evidence and a clear point of view.",
    "useWhen": "Testing assumptions, grounding strategy, or building an evidence base.",
    "url": "https://docs.google.com/document/d/1YAsRSTpx_yeNCTHsguAQ3t7F3zY79UUh/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 1
  },
  {
    "id": "doc-68",
    "title": "AI Capability Ceilings DataBook 1",
    "category": "Research & Signals",
    "status": "Reference",
    "format": "Interactive",
    "duration": "Reference",
    "audience": "Strategy & research teams",
    "brief": "An interactive evidence companion to the Capability Ceilings research paper.",
    "useWhen": "Testing assumptions, grounding strategy, or building an evidence base.",
    "url": "https://drive.google.com/file/d/1dHr20f6ryvlnrOE0Fgl7n_hlL9o4V6-5/view?usp=drivesdk",
    "sourceFiles": 1
  },
  {
    "id": "doc-73",
    "title": "AI Capability Ceilings Research Paper",
    "category": "Research & Signals",
    "status": "Reference",
    "format": "Document",
    "duration": "Reference",
    "audience": "Strategy & research teams",
    "brief": "Research on the shift in value from raw model capability toward the reliability of memory, tools, integration, and surrounding systems.",
    "useWhen": "Testing assumptions, grounding strategy, or building an evidence base.",
    "url": "https://docs.google.com/document/d/1gqAtKSeQQsyMKOaDH2nG04GKvSzN3con/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 1
  },
  {
    "id": "doc-82",
    "title": "ai-news-2026-06-08",
    "category": "Research & Signals",
    "status": "Reference",
    "format": "Working note",
    "duration": "Reference",
    "audience": "Strategy & research teams",
    "brief": "A research and signal document that provides context for enterprise AI strategy and implementation choices.",
    "useWhen": "Testing assumptions, grounding strategy, or building an evidence base.",
    "url": "https://drive.google.com/file/d/1W49cf6N4N07IHEzx3GeG634Xm9FcjKzP/view?usp=drivesdk",
    "sourceFiles": 1
  },
  {
    "id": "doc-75",
    "title": "BCG AI Implementation Scaling White Paper",
    "category": "Research & Signals",
    "status": "Reference",
    "format": "Document",
    "duration": "Reference",
    "audience": "Strategy & research teams",
    "brief": "A research or strategy reference on bcg ai implementation scaling, used to ground decisions in evidence and a clear point of view.",
    "useWhen": "Testing assumptions, grounding strategy, or building an evidence base.",
    "url": "https://docs.google.com/document/d/14DljF0WWjMlFKcdKvOJMlziOfC8yE1Lz/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 1
  },
  {
    "id": "doc-76",
    "title": "BCG AI Scaling White Paper",
    "category": "Research & Signals",
    "status": "Reference",
    "format": "Document",
    "duration": "Reference",
    "audience": "Strategy & research teams",
    "brief": "A research or strategy reference on bcg ai scaling, used to ground decisions in evidence and a clear point of view.",
    "useWhen": "Testing assumptions, grounding strategy, or building an evidence base.",
    "url": "https://docs.google.com/document/d/1LlTBbKbJsy2XUVFcSSLSXgt_4xmTa6We/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 1
  },
  {
    "id": "doc-80",
    "title": "Before the Chain AI Workflow Redesign White Paper",
    "category": "Research & Signals",
    "status": "Reference",
    "format": "Document",
    "duration": "Reference",
    "audience": "Strategy & research teams",
    "brief": "Explains why task chaining only creates value after upstream context, authority, and ambiguity are made manageable.",
    "useWhen": "Testing assumptions, grounding strategy, or building an evidence base.",
    "url": "https://docs.google.com/document/d/1KxxByKUxhnXXnkoBbvktXgItLDTfVzon/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 1
  },
  {
    "id": "doc-67",
    "title": "capability",
    "category": "Research & Signals",
    "status": "Reference",
    "format": "Interactive",
    "duration": "Reference",
    "audience": "Strategy & research teams",
    "brief": "A research and signal document that provides context for enterprise AI strategy and implementation choices.",
    "useWhen": "Testing assumptions, grounding strategy, or building an evidence base.",
    "url": "https://drive.google.com/file/d/1z-Z5Rw9nkIrmkPVWsUdUKE_QDqzFgcXt/view?usp=drivesdk",
    "sourceFiles": 1
  },
  {
    "id": "doc-72",
    "title": "Day 1 v3",
    "category": "Research & Signals",
    "status": "Reference",
    "format": "PDF",
    "duration": "Reference",
    "audience": "Strategy & research teams",
    "brief": "A research and signal document that provides context for enterprise AI strategy and implementation choices.",
    "useWhen": "Testing assumptions, grounding strategy, or building an evidence base.",
    "url": "https://drive.google.com/file/d/1Obi7xoGwXBHswxMoO5B25mPx_1Bk8TTY/view?usp=drivesdk",
    "sourceFiles": 1
  },
  {
    "id": "doc-70",
    "title": "Emerging AI Ecosystem Reliability",
    "category": "Research & Signals",
    "status": "Reference",
    "format": "Document",
    "duration": "Reference",
    "audience": "Strategy & research teams",
    "brief": "A research note on the reliability of the surrounding AI ecosystem and the controls required for enterprise use.",
    "useWhen": "Testing assumptions, grounding strategy, or building an evidence base.",
    "url": "https://docs.google.com/document/d/1etzo5Sp4k31dOKin52cbS--g3w8DOaHJ/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 1
  },
  {
    "id": "doc-77",
    "title": "linkedin-talent-velocity-advantage-report",
    "category": "Research & Signals",
    "status": "Reference",
    "format": "PDF",
    "duration": "Reference",
    "audience": "Strategy & research teams",
    "brief": "A research or strategy reference on linkedin-talent-velocity-advantage-, used to ground decisions in evidence and a clear point of view.",
    "useWhen": "Testing assumptions, grounding strategy, or building an evidence base.",
    "url": "https://drive.google.com/file/d/1plrhmOv1zMXFM45Ua8fGpiR5aSVfkwuZ/view?usp=drivesdk",
    "sourceFiles": 1
  },
  {
    "id": "doc-81",
    "title": "personal-agent-white-paper",
    "category": "Research & Signals",
    "status": "Reference",
    "format": "Document",
    "duration": "Reference",
    "audience": "Strategy & research teams",
    "brief": "Lessons from a live personal agent about state, tool contracts, observability, security, deployment discipline, and what transfers to enterprise work.",
    "useWhen": "Testing assumptions, grounding strategy, or building an evidence base.",
    "url": "https://docs.google.com/document/d/1Tdw98DKOg3jMvVQtkAXUeEwEl_PJBbu-/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 1
  },
  {
    "id": "doc-71",
    "title": "The Agent Harness Wars",
    "category": "Research & Signals",
    "status": "Reference",
    "format": "Document",
    "duration": "Reference",
    "audience": "Strategy & research teams",
    "brief": "A research perspective on the competition shifting from models toward agent runtimes, tools, memory, observability, and control systems.",
    "useWhen": "Testing assumptions, grounding strategy, or building an evidence base.",
    "url": "https://docs.google.com/document/d/1uygwTOL6tBeQekxzrheEkrPhfyM0rFHf/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 1
  },
  {
    "id": "doc-66",
    "title": "The Fracture The Queue The Handshake",
    "category": "Research & Signals",
    "status": "Reference",
    "format": "Document",
    "duration": "Reference",
    "audience": "Strategy & research teams",
    "brief": "A research and signal document that provides context for enterprise AI strategy and implementation choices.",
    "useWhen": "Testing assumptions, grounding strategy, or building an evidence base.",
    "url": "https://docs.google.com/document/d/1q0y6U5quqNjN0UX-bAHIuIjlJuFUu10t/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 1
  },
  {
    "id": "doc-65",
    "title": "The Handshake",
    "category": "Research & Signals",
    "status": "Reference",
    "format": "Document",
    "duration": "Reference",
    "audience": "Strategy & research teams",
    "brief": "A research and signal document that provides context for enterprise AI strategy and implementation choices.",
    "useWhen": "Testing assumptions, grounding strategy, or building an evidence base.",
    "url": "https://docs.google.com/document/d/1jUTMUTRTYCoYUPoMqFUkmIpnFwOMGF7a/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 1
  },
  {
    "id": "doc-78",
    "title": "The Intelligence Layer Enterprise Capability Paper",
    "category": "Research & Signals",
    "status": "Reference",
    "format": "Document",
    "duration": "Reference",
    "audience": "Strategy & research teams",
    "brief": "Argues for an enterprise Intelligence Layer that makes intent, context, source authority, permissions, and output flow legible before workflow redesign.",
    "useWhen": "Testing assumptions, grounding strategy, or building an evidence base.",
    "url": "https://docs.google.com/document/d/12GDoVQA5wTS9FOtDM2P2H-xA2fZt1t8I/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 1
  },
  {
    "id": "doc-69",
    "title": "The Intelligence Layer in Enterprise AI Stacks",
    "category": "Research & Signals",
    "status": "Reference",
    "format": "Document",
    "duration": "Reference",
    "audience": "Strategy & research teams",
    "brief": "A research and signal document that provides context for enterprise AI strategy and implementation choices.",
    "useWhen": "Testing assumptions, grounding strategy, or building an evidence base.",
    "url": "https://docs.google.com/document/d/1u2gXHKHxNYJLYovzOBjyO7WPvgE-1J8Q/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 1
  },
  {
    "id": "doc-79",
    "title": "The Work Beneath The Workflow Operational Layer Paper",
    "category": "Research & Signals",
    "status": "Reference",
    "format": "Document",
    "duration": "Reference",
    "audience": "Strategy & research teams",
    "brief": "Explains why role redesign must begin with the operational layer: real requests, judgment, systems, exceptions, and handoffs.",
    "useWhen": "Testing assumptions, grounding strategy, or building an evidence base.",
    "url": "https://docs.google.com/document/d/1bnYMHt6IApapzZz0c4WF4lnXcf9xQnvG/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 1
  },
  {
    "id": "doc-115",
    "title": "five-file-method-SKILL",
    "category": "Build Methods",
    "status": "Current",
    "format": "Working note",
    "duration": "5–10 min brief",
    "audience": "Builders & technical leads",
    "brief": "A reusable build instruction that turns five-file-method- into a repeatable workflow with explicit checks.",
    "useWhen": "Turning a recurring build or audit practice into a reusable method.",
    "url": "https://drive.google.com/file/d/1bR32vvOW6W6LeeJl2oWwYqAgx3fnjh5b/view?usp=drivesdk",
    "sourceFiles": 1
  },
  {
    "id": "doc-113",
    "title": "rampstack-check-SKILL",
    "category": "Build Methods",
    "status": "Current",
    "format": "Working note",
    "duration": "5–10 min brief",
    "audience": "Builders & technical leads",
    "brief": "A reusable build instruction that turns rampstack-check- into a repeatable workflow with explicit checks.",
    "useWhen": "Turning a recurring build or audit practice into a reusable method.",
    "url": "https://drive.google.com/file/d/1pt7gf9TOtxCa0yS0HkiM4sjdtQjHcaAn/view?usp=drivesdk",
    "sourceFiles": 1
  },
  {
    "id": "doc-114",
    "title": "rampstack-SKILL",
    "category": "Build Methods",
    "status": "Current",
    "format": "Working note",
    "duration": "5–10 min brief",
    "audience": "Builders & technical leads",
    "brief": "A reusable build instruction that turns rampstack- into a repeatable workflow with explicit checks.",
    "useWhen": "Turning a recurring build or audit practice into a reusable method.",
    "url": "https://drive.google.com/file/d/1laB4mBUdVlTL4OiEP1bZqVwrpZNj9cZP/view?usp=drivesdk",
    "sourceFiles": 1
  },
  {
    "id": "doc-103",
    "title": "IGNITE Workshop",
    "category": "Archive",
    "status": "Archive",
    "format": "Document",
    "duration": "1-day program",
    "audience": "Employees & facilitators",
    "brief": "An Academy asset for ignite workshop, including the audience, learning flow, outcomes, and practical leave-behinds.",
    "useWhen": "Understanding prior versions or the evolution of the system.",
    "url": "https://docs.google.com/document/d/1YarJ-KIEozdLHRYNfOAolLiZEDFPxMLx/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 2
  },
  {
    "id": "doc-104",
    "title": "Leadership AI Strategy Session",
    "category": "Archive",
    "status": "Archive",
    "format": "Document",
    "duration": "5–10 min brief",
    "audience": "Leaders",
    "brief": "A historical version retained for context. Use the current materials for active guidance and this source only to understand how the thinking evolved.",
    "useWhen": "Understanding prior versions or the evolution of the system.",
    "url": "https://docs.google.com/document/d/1snElBXD7k4_MQtbJX6LEeZNm1tdhdJqu/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 2
  },
  {
    "id": "doc-105",
    "title": "Project Zero",
    "category": "Archive",
    "status": "Archive",
    "format": "Document",
    "duration": "5–10 min brief",
    "audience": "Enterprise teams",
    "brief": "A historical version retained for context. Use the current materials for active guidance and this source only to understand how the thinking evolved.",
    "useWhen": "Understanding prior versions or the evolution of the system.",
    "url": "https://docs.google.com/document/d/1ozwRjx-stjrP98q28BdQG9Pk8fHavPyt/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 2
  },
  {
    "id": "doc-49",
    "title": "Project Zero and RampStack are AI literacy infrastructure",
    "category": "Archive",
    "status": "Archive",
    "format": "Document",
    "duration": "5–10 min brief",
    "audience": "Enterprise teams",
    "brief": "A historical version retained for context. Use the current materials for active guidance and this source only to understand how the thinking evolved.",
    "useWhen": "Understanding prior versions or the evolution of the system.",
    "url": "https://docs.google.com/document/d/1VF5H3BTXTdyauMpKuKYYOIm8f_FOL4Gh/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 1
  },
  {
    "id": "doc-50",
    "title": "rampstack agent audit addendum (1)",
    "category": "Archive",
    "status": "Archive",
    "format": "Document",
    "duration": "5–10 min brief",
    "audience": "Enterprise teams",
    "brief": "A historical version retained for context. Use the current materials for active guidance and this source only to understand how the thinking evolved.",
    "useWhen": "Understanding prior versions or the evolution of the system.",
    "url": "https://docs.google.com/document/d/19ipU7m0wQ9YTstdtwNN3vJSrHs7LSzJG/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 1
  },
  {
    "id": "doc-51",
    "title": "RampStack V4 Internal Manual (1)",
    "category": "Archive",
    "status": "Archive",
    "format": "Document",
    "duration": "5–10 min brief",
    "audience": "Enterprise teams",
    "brief": "A historical version retained for context. Use the current materials for active guidance and this source only to understand how the thinking evolved.",
    "useWhen": "Understanding prior versions or the evolution of the system.",
    "url": "https://docs.google.com/document/d/1Vtyf0q_et-rpDjxfbAAzE296v2yJzxNV/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 1
  },
  {
    "id": "doc-48",
    "title": "Situating an Automation Training Intelligence Layer",
    "category": "Archive",
    "status": "Archive",
    "format": "Document",
    "duration": "5–10 min brief",
    "audience": "Enterprise teams",
    "brief": "A historical version retained for context. Use the current materials for active guidance and this source only to understand how the thinking evolved.",
    "useWhen": "Understanding prior versions or the evolution of the system.",
    "url": "https://docs.google.com/document/d/1T07f2ZggVZBGUoEx7Kbln-E9y3SzVXBP/edit?usp=drivesdk&ouid=100112849859205694412&rtpof=true&sd=true",
    "sourceFiles": 1
  }
];

